Authentification system
Fiphee/art_web_app pull request #2
Opened 2021-03-21 14:40 UTC by Fiphee

2021-03-22 07:11 UTC, mihaitzzza commented on art_web_app/views.py
> +    return render(request, "home.html", context)
You don't have to send the user in context. You'll have access to `user` directly through Django's context processors.

2021-03-22 07:11 UTC, mihaitzzza commented on users/models.py
> +@receiver(post_save, sender=AuthUserModel)
Move this into `signals.py` and import the file in `apps.py`'s `ready` function. We'll discuss this this week, anyway.

2021-03-22 07:11 UTC, mihaitzzza commented on users/models.py
> +    instance.profile.save()
I would link the `save` on L35. Plus you don't need to save the profile anytime, only when you create it.

2021-03-22 07:11 UTC, mihaitzzza commented on users/templates/register.html
> +    <p>Already have an account? Login <a href="/login">here</a></p>
I would used named URLs. E.g. `href={% url 'users:login' %}` or just `{% url 'login' %}` since you've included the auth links directly in project.

2021-03-26 19:21 UTC, mihaivladu requested changes

2021-03-26 19:21 UTC, mihaivladu commented on art_web_app/views.py
> +    context = {}
You don’t need this, why not delete it?

2021-03-26 19:21 UTC, mihaivladu commented on users/signals.py
> +def update_profile_signal(instance, created, **kwargs):
Just remind me...why do you need do update the profile when the user is CREATED?

2021-03-26 19:21 UTC, mihaivladu commented on users/views.py
> +            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
Do you really have to specify the backend? I think it will use the default one.

2021-03-26 19:21 UTC, mihaivladu commented on art_web_app/settings.py
Do you want to use own validators?

2021-03-27 07:00 UTC, mihaitzzza approved these changes

2021-03-27 08:40 UTC, merged